openapi: "3.0.0"
info:
  version: 1.0.0
  title: MusicPlay User API
  description: Helps manage user accounts on the MusicPlay application.
servers:
  - url: https://musicplay.io/api/v1/users
security:
  - oauth2: []
paths:
  /:
    get:
      summary: Get all users.
      operationId: getAllUsers
      security:
        - oauth2: ["read:user"]
      tags:
        - users
        - internal
  /{user-id}:
    get:
      summary: Get user profile.
      operationId: getUserProfile
      security:
        - oauth2: ["read:user"]
      tags:
        - user profile
    put:
      summary: Update user profile.
      operationId: updateUserProfile
      security:
        - oauth2: ["write:user"]
      tags:
        - user profile
  /{user-id}/playlists:
    get:
      summary: Get playlists associated with the user account.
      operationId: getUserPlaylists
      security:
        - oauth2: ["read:user"]      
      tags:
        - playlists
    post:
      summary: Add new playlist to user account.
      operationId: addUserPlaylist
      security:
        - oauth2: ["write:user"]      
      tags:
        - playlists
  /playlists/{playlist-id}:
    get:
      summary: Get user playlist metadata.
      operationId: getPlaylist
      security:
        - oauth2: ["read:playlist"]      
      tags:
        - playlists
    delete:
      summary: Delete user playlist.
      operationId: deletePlaylist
      security:
        - oauth2: ["write:playlist"]      
      tags:
        - playlists   
  /playlists/{playlist-id}/tracks:
    get:
      summary: Get tracks associated with a user playlist.
      operationId: getPlaylistTracks
      security:
        - oauth2: ["read:playlist"]      
      tags:
        - playlist tracks
    post:
      summary: Add new playlist track.
      operationId: addPlaylistTrack
      security:
        - oauth2: ["write:playlist"]          
      tags:
        - playlist tracks
  /tracks/{track-id}:
    get:
      summary: Get playlist track.
      operationId: getUserPlaylistTrack
      security:
        - oauth2: ["read:track"]      
      tags:
        - playlist tracks
    delete:
      summary: Delete user playlist track.
      operationId: deleteUserPlaylistTrack
      security:
        - oauth2: ["write:playlist"]          
      tags:
        - playlist tracks
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://musicplay.io/api/oauth/authorize
          tokenUrl: https://musicplay.io/api/oauth/token
          scopes:
            write:user: modify user profile in your account
            read:user: read user profile
            write:playlist: modify user playlist
            read:playlist: read user playlist
            write:playlist-track: modify user playlist track
            read:playlist-track: read user playlist track